# Used by: get-projects — Git URL prefix aliases for short repo references
repositories:
  securesign: git@github.com:securesign
  release-engineering: git@gitlab.cee.redhat.com:releng

# Used by: get-projects — Named sets of repos to clone/fetch and checkout
projects:
  rhtas:
    default_branch: main
    repos:
      - url: securesign/certificate-transparency-go
      - url: securesign/cosign
      - url: securesign/fulcio
      - url: securesign/gitsign
      - url: securesign/rekor
      - url: securesign/rekor-monitor
      - url: securesign/rekor-search-ui
      - url: securesign/segment-backup-job
      - url: securesign/timestamp-authority
      - url: securesign/tough
        branch: develop
      - url: securesign/trillian
      - url: securesign/artifact-signer-ansible
      - url: securesign/secure-sign-operator
      - url: securesign/fbc
      - url: securesign/sigstore-e2e
      - url: securesign/structural-tests
      - url: securesign/releases
      - url: securesign/pipelines

  rhtas-1.4:
    default_branch: release-1.4
    repos:
      - url: securesign/certificate-transparency-go
      - url: securesign/cosign
      - url: securesign/fulcio
      - url: securesign/gitsign
      - url: securesign/rekor
      - url: securesign/rekor-monitor
      - url: securesign/rekor-search-ui
      - url: securesign/timestamp-authority
      - url: securesign/tough
      - url: securesign/trillian
      - url: securesign/artifact-signer-ansible
      - url: securesign/secure-sign-operator
      - url: securesign/fbc
        branch: main
      - url: securesign/sigstore-e2e
      - url: securesign/structural-tests
        branch: main
      - url: securesign/releases
        branch: release-1.4.2
      - url: securesign/pipelines
        branch: main
      - url: release-engineering/konflux-release-data
        branch: main

  rhtas-1.3:
    default_branch: release-1.3
    repos:
      - url: securesign/certificate-transparency-go
      - url: securesign/cosign
      - url: securesign/fulcio
      - url: securesign/gitsign
      - url: securesign/rekor
      - url: securesign/rekor-monitor
      - url: securesign/rekor-search-ui
      - url: securesign/segment-backup-job
      - url: securesign/timestamp-authority
      - url: securesign/tough
      - url: securesign/trillian
      - url: securesign/artifact-signer-ansible
      - url: securesign/secure-sign-operator
      - url: securesign/fbc
        branch: main
      - url: securesign/sigstore-e2e
      - url: securesign/structural-tests
        branch: main
      - url: securesign/releases
        branch: release-1.3.6
      - url: securesign/pipelines
        branch: main

  releases-1.4.3:
    repos:
      - url: securesign/releases
        branch: main
        dir: releases-main
      - url: securesign/releases
        branch: release-1.4.3
        dir: releases-release-1.4.3
      - url: securesign/releases
        branch: release-pco-1.0.2
        dir: releases-release-pco-1.0.2
      - url: securesign/releases
        branch: release-mt-go-0.0.3
        dir: releases-release-mt-go-0.0.3
      - url: securesign/releases
        branch: release_mt_1.0.3
        dir: releases-release_mt_1.0.3
      - url: securesign/releases
        branch: release-mvo-0.1.2
        dir: releases-release-mvo-0.1.2


  rhtas-own:
    default_branch: main
    repos:
      - url: securesign/actions
      - url: securesign/artifact-signer-ansible
      - url: securesign/fbc
      - url: securesign/model-validation-operator
      - url: securesign/pipelines
      - url: securesign/policy-controller-operator
      - url: securesign/releases
      - url: securesign/renovate-config
      - url: securesign/rekor-search-ui
      - url: securesign/rhtas-benchmark
      - url: securesign/rhtas-console
      - url: securesign/rhtas-console-ui
      - url: securesign/secure-sign-operator
      - url: securesign/segment-backup-job
      - url: securesign/sigstore-e2e
      - url: securesign/structural-tests
      - url: securesign/tufcli

  rhtas-fork:
    default_branch: main
    repos:
      - url: securesign/certificate-transparency-go
      - url: securesign/cosign
      - url: securesign/fulcio
      - url: securesign/gitsign
      - url: securesign/model-transparency
      - url: securesign/model-transparency-go
      - url: securesign/policy-controller
      - url: securesign/rekor
      - url: securesign/rekor-monitor
      - url: securesign/timestamp-authority
      - url: securesign/tough
      - url: securesign/trillian

  rhtas-tests:
    default_branch: main
    repos:
      - url: securesign/sigstore-e2e
      - url: securesign/structural-tests
      - url: securesign/releases

  release-data:
    default_branch: main
    repos:
      - url: release-engineering/konflux-release-data

  rhtas-all-main:
    default_branch: main
    repos:
      - url: securesign/actions
      - url: securesign/artifact-signer-ansible
      - url: securesign/certificate-transparency-go
      - url: securesign/cosign
      - url: securesign/fbc
      - url: securesign/fulcio
      - url: securesign/gitsign
      - url: securesign/model-transparency
      - url: securesign/model-transparency-go
      - url: securesign/model-validation-operator
      - url: securesign/pipelines
      - url: securesign/policy-controller
      - url: securesign/policy-controller-operator
      - url: securesign/rekor
      - url: securesign/rekor-monitor
      - url: securesign/rekor-search-ui
      - url: securesign/releases
      - url: securesign/rhtas-benchmark
      - url: securesign/rhtas-console
      - url: securesign/rhtas-console-ui
      - url: securesign/secure-sign-operator
      - url: securesign/segment-backup-job
      - url: securesign/sigstore-e2e
      - url: securesign/structural-tests
      - url: securesign/timestamp-authority
      - url: securesign/tough
      - url: securesign/trillian
      - url: securesign/tufcli

# Used by: check-tags-n-branches — Repos grouped by release branches and tags to verify
release_groups:
  securesign:
    release_branches:
      - release-1.3
      - release-1.4
    release_tags:
      - rhtas-v1.3.5
      - rhtas-v1.3.6
      - rhtas-v1.4.1
      - rhtas-v1.4.2
      - rhtas-v1.4.3
    repos:
      - securesign/certificate-transparency-go
      - securesign/cosign
      - securesign/fulcio
      - securesign/gitsign
      - securesign/rekor
      - securesign/rekor-monitor
      - securesign/rekor-search-ui
      - securesign/timestamp-authority
      - securesign/tough
      - securesign/trillian
      - securesign/artifact-signer-ansible

  tags-only:
    release_tags:
      - rhtas-v1.3.5
      - rhtas-v1.3.6
      - rhtas-v1.4.1
      - rhtas-v1.4.2
      - rhtas-v1.4.3
    repos:
      - securesign/fbc

  branches-only:
    release_branches:
      - release-1.3
      - release-1.4
    repos:
      - securesign/sigstore-e2e

  main-only:
    repos:
      - securesign/structural-tests
      - securesign/pipelines

  releases:
    release_branches:
      - release-1.3.5
      - release-1.3.6
      - release-1.4.1
      - release-1.4.2
      - release-1.4.3
    repos:
      - securesign/releases

  operator:
    release_branches:
      - release-1.3
      - release-1.4
    release_tags:
      - v1.3.5
      - v1.3.6
      - v1.4.1
      - v1.4.2
      - v1.4.3
    repos:
      - securesign/secure-sign-operator

  segment-backup-job:
    release_branches:
      - release-1.3
    release_tags:
      - rhtas-v1.3.5
      - rhtas-v1.3.6
    repos:
      - securesign/segment-backup-job

  model-transparency:
    release_branches:
      - release-1.0
    release_tags:
      - rhtas-v1.0.3
    repos:
      - securesign/model-transparency

  policy-controller:
    release_branches:
      - release-1.0
    release_tags:
      - rhtas-v1.0.0
      - rhtas-v1.0.1
      - rhtas-v1.0.2
    repos:
      - securesign/policy-controller
      - securesign/policy-controller-operator

  tech-preview:
    repos:
      - securesign/model-transparency-go
      - securesign/rhts-console
      - securesign/rhts-console-ui
      - securesign/model-validation-operator